"""Main FastAPI application.

Responsibility: Assemble routers, middleware and application
configuration.
"""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from starlette.middleware.sessions import SessionMiddleware
from uvicorn.middleware.proxy_headers import ProxyHeadersMiddleware

from capiba.api import portal
from capiba.api.routers import evidence, ranking, signals
from capiba.config import PORTAL_SESSION_SECRET
from capiba.notification.scheduler import start_notification_scheduler

logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Starts/stops the notification scheduler with the API process.

    The scheduler (periodic quality reports) only runs when
    ``NOTIFICATION_RECIPIENTS`` is configured; otherwise this is a no-op.
    """
    scheduler = start_notification_scheduler()
    try:
        yield
    finally:
        if scheduler is not None:
            scheduler.stop()


app = FastAPI(
    title="Capiba",
    description="Cruzamento e Análise de Padrões e Indícios em Bases Abertas",
    version="0.1.0",
    lifespan=lifespan,
)

# Trust X-Forwarded-* headers from the Traefik ingress so URLs generated by
# the portal OIDC flow use https://<host>:8443 behind the TLS terminator.
app.add_middleware(ProxyHeadersMiddleware, trusted_hosts="*")

# Static assets for the portal (logo, etc.)
_STATIC_DIR = Path(__file__).resolve().parent / "static"
app.mount("/static", StaticFiles(directory=str(_STATIC_DIR)), name="static")

# Signed-cookie sessions for the portal SSO flow; https_only=False because the
# cluster also serves plain HTTP on 8088/localhost (port-forward).
app.add_middleware(
    SessionMiddleware, secret_key=PORTAL_SESSION_SECRET, https_only=False
)

app.include_router(portal.router)
app.include_router(signals.router)
app.include_router(ranking.router)
app.include_router(evidence.router)


@app.get("/health")
async def health() -> dict[str, str]:
    """Health check endpoint."""
    return {"status": "ok"}
