"""Atomic transformation tasks.

Responsibility: pure functions (``validate_contracts``, ``persist_contracts``)
implementing steps of the ingestion pipeline, with no Airflow dependency,
reused by ``capiba.pipeline.runner``. The ``task_*`` wrappers adapt the
declarative pipeline steps to the Airflow context (XCom, ``ds``) and are
called by the DAG operators generated by ``dags/pipeline_factory.py`` from
``dags/pipelines/*.yaml``; ``scripts/ingestion.py`` executes the same specs
through the runner, without Airflow.

``task_run_pipeline`` is the entrypoint of the declarative framework: the
DAGs call it with the spec path, delegating execution to
``capiba.pipeline.runner``.
"""

from __future__ import annotations

import gzip
import json
import logging
from datetime import UTC, date, datetime
from typing import Any

import pandas as pd

from capiba.config import (
    DBT_PROJECT_DIR,
    DETECTION_ENTITY_THRESHOLD,
    TSE_ELECTION_YEAR,
)
from capiba.db.arangodb import get_capiba_db
from capiba.detection.entities import resolve_entities
from capiba.ingestion.crawler_pncp import fetch_contract_terms, parse_control_number
from capiba.ingestion.crawler_querido_diario import (
    download_gazette_text,
    text_file_name,
)
from capiba.ingestion.normalizer import Contract
from capiba.ingestion.persistence import bulk_upsert_cnpj, bulk_upsert_contracts
from capiba.ingestion.validator import checksum, detect_duplicates
from capiba.notification.alerts import notify_validation_failure
from capiba.pipeline import lake
from capiba.pipeline.registry import (
    DESTINATION_REGISTRY,
    DUMP_PARSER_REGISTRY,
    NORMALIZER_REGISTRY,
    SOURCE_REGISTRY,
)
from capiba.pipeline.window import resolve_window
from capiba.quality.lineage import LineageTracker

logger = logging.getLogger(__name__)


def _lake_run_date(context: dict[str, Any]) -> date | None:
    """Extracts the run date from the Airflow context.

    Airflow 3 removed ``ds`` from the task context: use ``logical_date``
    (falling back to the DAG run's ``run_after``, which manual runs set),
    and still accept the legacy ``ds`` key for offline callers and tests.
    """
    run_dt = context.get("logical_date")
    if run_dt is None:
        dag_run = context.get("dag_run")
        run_dt = getattr(dag_run, "run_after", None)
    if isinstance(run_dt, datetime):
        return run_dt.date()
    if run_dt is not None:
        return date.fromisoformat(str(run_dt)[:10])
    ds = context.get("ds")
    return date.fromisoformat(ds) if ds else None


def validate_contracts(
    contracts: list[dict[str, Any]],
    normalization_errors: int = 0,
) -> dict[str, Any]:
    """Validates normalized contracts (checksum and duplicates).

    Args:
        contracts: Serializable normalized contracts.
        normalization_errors: Errors recorded in the normalization step.

    Returns:
        Validation report.
    """
    logger.info("Validating %d contracts", len(contracts))

    raw_bytes = json.dumps(contracts, sort_keys=True).encode()
    chk = checksum(raw_bytes)
    duplicates = detect_duplicates(contracts, key="id")

    report = {
        "total": len(contracts),
        "checksum": chk,
        "duplicates": len(duplicates),
        "duplicate_ids": duplicates,
        "normalization_errors": normalization_errors,
        "valid": len(duplicates) == 0,
    }

    logger.info("Validation: %s", report)
    return report


def validate_documents(
    records: list[dict[str, Any]],
    download_errors: int = 0,
) -> dict[str, Any]:
    """Validates raw document records of the documents_collect formula.

    Same report shape as ``validate_contracts`` (compatible with the
    validation alerts and the quality monitor), keyed by ``url`` — the
    gazette records have no ``id`` field. ``download_errors`` counts the
    text-download failures of the ``download_<source>_texts`` step.

    Args:
        records: Raw document records (e.g. Querido Diário gazettes).
        download_errors: Errors recorded in the text-download step.

    Returns:
        Validation report.
    """
    logger.info("Validating %d documents", len(records))
    duplicates = detect_duplicates([r for r in records if r.get("url")], key="url")
    report = {
        "total": len(records),
        "duplicates": len(duplicates),
        "duplicate_ids": duplicates,
        "normalization_errors": download_errors,
        "valid": len(duplicates) == 0,
    }
    logger.info("Validation: %s", report)
    return report


def persist_document_texts(
    source_name: str,
    records: list[dict[str, Any]],
    run_date: date | None = None,
) -> dict[str, Any]:
    """Downloads the extracted text of each document record to the bronze layer.

    Shared core of the documents_collect ``download_<source>_texts`` step
    (runner and Airflow task): for each record with ``txt_url``, uploads the
    text under a deterministic file name (``text_file_name``); files already
    present in the bronze layer for the run date are skipped, so a retried
    task resumes where it stopped. Best-effort per record: failures are
    counted and logged, never fatal. Records gain ``text_bronze_file`` with
    the persisted file name.

    Args:
        source_name: Source name (e.g. ``querido_diario``).
        records: Raw document records.
        run_date: Partition date; defaults to today (UTC).

    Returns:
        Summary (texts downloaded/skipped, errors).
    """
    try:
        existing = {
            key.rsplit("/", 1)[-1]
            for key in lake.list_bronze_files(source_name, run_date)
        }
    except Exception as exc:
        logger.warning(
            "Failed to list %s bronze files; downloading everything: %s",
            source_name,
            exc,
        )
        existing = set()

    downloaded = skipped = errors = 0
    for record in records:
        txt_url = record.get("txt_url")
        if not txt_url:
            continue
        filename = text_file_name(record)
        if filename in existing:
            record["text_bronze_file"] = filename
            skipped += 1
            continue
        try:
            data = download_gazette_text(txt_url)
            lake.write_bronze_file(source_name, filename, data, run_date=run_date)
        except Exception as exc:
            errors += 1
            logger.warning("Failed to persist document text %s: %s", txt_url, exc)
            continue
        record["text_bronze_file"] = filename
        downloaded += 1

    summary: dict[str, Any] = {
        "source": source_name,
        "texts_downloaded": downloaded,
        "texts_skipped": skipped,
        "errors": errors,
    }
    logger.info("Document texts persisted for %s: %s", source_name, summary)
    return summary


def terms_checkpoint_name(numero_controle: str) -> str:
    """Deterministic bronze checkpoint name of a contract's terms payload.

    Layout ``<cnpj>/<ano>/<sequencial>.json.gz`` under
    ``<source>/files/dt=<run>/`` (PR-D-05b § 4).

    Raises:
        ValueError: If the control number does not match the PNCP layout.
    """
    cnpj, ano, sequencial = parse_control_number(numero_controle)
    return f"{cnpj}/{ano}/{sequencial}.json.gz"


def persist_contract_terms(
    source_name: str,
    records: list[dict[str, Any]],
    run_date: date | None = None,
) -> dict[str, Any]:
    """Fetches and persists the registered terms of each contract (PR-D-05b).

    For each record with ``numeroControlePNCP``, fetches the terms from the
    PNCP terms endpoint and uploads the payload (control number + term
    list, gzip JSON) to the bronze layer under the deterministic
    per-contract checkpoint name; contracts already persisted for the run
    date are skipped, so a retried crawl resumes where it stopped and never
    duplicates. Best-effort per contract: fetch/persist failures are
    counted and logged (the contract keeps no checkpoint and is retried on
    the next run), never fatal. Contracts without terms (HTTP 204) persist
    an empty list — "no terms" is data (flags compute 0), not failure;
    only a failed query computes NULL flags downstream. Records gain
    ``terms_bronze_file`` with the persisted checkpoint name.

    Args:
        source_name: Source name (``pncp_contract_terms``).
        records: Contract descriptors carrying ``numeroControlePNCP``.
        run_date: Partition date; defaults to today (UTC).

    Returns:
        Summary (terms fetched/skipped, errors).
    """
    run_date = run_date or datetime.now(UTC).date()
    prefix = f"{source_name}/files/dt={run_date.isoformat()}/"
    try:
        existing = {
            key.removeprefix(prefix)
            for key in lake.list_bronze_files(source_name, run_date)
        }
    except Exception as exc:
        logger.warning(
            "Failed to list %s bronze files; fetching everything: %s",
            source_name,
            exc,
        )
        existing = set()

    fetched = skipped = errors = 0
    for record in records:
        numero_controle = record.get("numeroControlePNCP")
        if not numero_controle:
            continue
        try:
            filename = terms_checkpoint_name(str(numero_controle))
            cnpj, ano, sequencial = parse_control_number(str(numero_controle))
        except ValueError as exc:
            errors += 1
            logger.warning("Invalid numeroControlePNCP %s: %s", numero_controle, exc)
            continue
        if filename in existing:
            record["terms_bronze_file"] = filename
            skipped += 1
            continue
        try:
            terms = fetch_contract_terms(cnpj, ano, sequencial)
            payload = {
                "numeroControlePNCP": numero_controle,
                "cnpj": cnpj,
                "ano": ano,
                "sequencial": sequencial,
                "terms": terms or [],
            }
            data = gzip.compress(json.dumps(payload, default=str).encode())
            lake.write_bronze_file(source_name, filename, data, run_date=run_date)
        except Exception as exc:
            errors += 1
            logger.warning("Failed to persist terms of %s: %s", numero_controle, exc)
            continue
        record["terms_bronze_file"] = filename
        fetched += 1

    summary: dict[str, Any] = {
        "source": source_name,
        "terms_fetched": fetched,
        "terms_skipped": skipped,
        "errors": errors,
    }
    logger.info("Contract terms persisted for %s: %s", source_name, summary)
    return summary


def persist_contracts(
    contracts_dict: list[dict[str, Any]],
    execution_date: str | None = None,
) -> dict[str, Any]:
    """Persists validated contracts in ArangoDB, recording lineage.

    Args:
        contracts_dict: Serializable normalized contracts.
        execution_date: Execution date (lineage metadata).

    Returns:
        Persistence summary.
    """
    logger.info("Persisting %d contracts", len(contracts_dict))

    tracker = LineageTracker()
    source_id = tracker.register_source(
        name="daily_ingestion",
        url="https://pncp.gov.br/api/consulta",
        api_type="REST",
        metadata={"execution_date": execution_date},
    )

    contracts = []
    for c in contracts_dict:
        try:
            contracts.append(Contract.model_validate(c))
        except Exception as e:
            logger.warning("Failed to revalidate contract for persistence: %s", e)

    try:
        db = get_capiba_db()
        summary = bulk_upsert_contracts(db, contracts, tracker=tracker)
        summary["lineage"] = tracker.export()
        summary["source_id"] = source_id
    except Exception as e:
        logger.error("Persistence failed: %s", e)
        summary = {"error": str(e)}

    return summary


def persist_cnpj_entities(execution_date: str | None = None) -> dict[str, Any]:
    """Persists the silver CNPJ entities in the ArangoDB graph, in batches.

    Reads the silver ``companies``/``partners`` tables batch by batch and
    bulk-upserts the FtM graph vertices (``companies``/``persons``) and
    ``ownership``/``directorship`` edges, so the large dump tables never
    materialize in memory. After the load, entity resolution writes
    ``same_as`` edges between person vertices at or above
    ``DETECTION_ENTITY_THRESHOLD`` — best-effort: a resolution failure is
    reported apart (``resolution_error``) and never fails the graph load.

    Args:
        execution_date: Execution date (metadata only).

    Returns:
        Persistence summary ``{companies, persons, edges, errors}`` plus
        ``same_as`` (or ``resolution_error``) — or ``{"error": ...}`` when
        the load itself fails.
    """
    totals: dict[str, Any] = {"companies": 0, "persons": 0, "edges": 0, "errors": 0}
    try:
        db = get_capiba_db()
        for entity in ("companies", "partners"):
            for batch in lake.read_silver_entities(entity):
                # Small import batches throttle the write rate: sustained
                # 1000-doc imports (~20k docs/s) OOMKilled the ArangoDB pod
                # on the first full graph load (2026-08-20).
                summary = bulk_upsert_cnpj(
                    db,
                    companies=batch if entity == "companies" else [],
                    partners=batch if entity == "partners" else [],
                    batch_size=250,
                )
                for key in totals:
                    totals[key] += summary[key]
    except Exception as e:
        logger.error("CNPJ persistence failed: %s", e)
        return {"error": str(e), **totals}

    try:
        resolution = resolve_entities(db, threshold=DETECTION_ENTITY_THRESHOLD)
        totals["same_as"] = resolution["same_as"]
    except Exception as e:
        logger.error("Entity resolution failed: %s", e)
        totals["resolution_error"] = str(e)

    logger.info("CNPJ graph load finished: %s", totals)
    return totals


def task_detect(**context: Any) -> dict[str, Any]:
    """Task: compute fraud signals over the silver contracts (gold table).

    Thin Airflow wrapper: the detection logic (silver/graph loading, the
    best-effort screening blocks, evidence, triage and alerts) lives in
    ``capiba.pipeline.detect_task.run_detection``; the lazy import avoids
    the circular dependency (``detect_task`` reuses ``_lake_run_date``
    from this module).

    Args:
        context: Airflow context.

    Returns:
        Detection summary (number of signals written).
    """
    from capiba.pipeline.detect_task import run_detection

    return run_detection(**context)


def _load_spec(spec_path: str) -> Any:
    """Loads a pipeline spec, populating formula/destination registries."""
    from capiba.pipeline.spec import load_spec

    return load_spec(spec_path)


def task_crawl_source(
    source_name: str, spec_path: str, **context: Any
) -> list[dict[str, Any]]:
    """Task: crawl a single source declared in the pipeline spec.

    The raw records are pushed to XCom under ``raw_<source_name>`` so later
    tasks (normalize, bronze destinations) can consume them.

    Args:
        source_name: Name of the source to crawl (must exist in the spec).
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        List of raw records.
    """
    run_date = _lake_run_date(context) or date.today()
    spec = _load_spec(spec_path)
    source = next((s for s in spec.sources if s.name == source_name), None)
    if source is None:
        raise ValueError(f"Source '{source_name}' not found in spec '{spec_path}'")

    date_range = resolve_window(source.window or spec.window, run_date)
    fetch = SOURCE_REGISTRY[source_name].fetch
    if fetch is None:
        raise ValueError(f"Source '{source_name}' has no record fetcher")

    logger.info("Crawling source '%s' for %s", source_name, run_date)
    records = fetch(date_range.start, date_range.end, **source.params)

    try:
        lake.write_bronze(source_name, records, run_date=run_date)
        lake.write_bronze_table(source_name, records, run_date=run_date)
    except Exception as e:
        logger.warning(
            "Failed to write %s payload to the bronze layer: %s", source_name, e
        )

    context["ti"].xcom_push(key=f"raw_{source_name}", value=records)
    return records


def task_download_source(
    source_name: str, spec_path: str, **context: Any
) -> dict[str, Any]:
    """Task: download a dump source declared in the pipeline spec.

    Each downloaded file is uploaded to the bronze layer immediately
    (and removed from the tempdir); on a retry, files already present in
    the bronze layer for the run date are skipped and re-entered into the
    manifest, so a pod restart no longer restarts a multi-GB dump from
    scratch. The manifest is pushed to XCom under ``manifest_<source_name>``.

    Args:
        source_name: Name of the dump source to download.
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Manifest payload (reference month and file list).
    """
    import hashlib
    import tempfile
    from pathlib import Path

    run_date = _lake_run_date(context) or date.today()
    spec = _load_spec(spec_path)
    source = next((s for s in spec.sources if s.name == source_name), None)
    if source is None:
        raise ValueError(f"Source '{source_name}' not found in spec '{spec_path}'")

    date_range = resolve_window(source.window or spec.window, run_date)
    if date_range.start is None:
        raise ValueError(f"Source '{source_name}' requires a bounded window")
    reference_month = date_range.start.strftime("%Y-%m")

    download = SOURCE_REGISTRY[source_name].download
    if download is None:
        raise ValueError(f"Source '{source_name}' has no dump downloader")

    logger.info("Downloading source '%s' for %s", source_name, reference_month)

    # Resume support: files already uploaded to the bronze layer by a
    # previous attempt are skipped and re-entered into the manifest (the
    # download tempdir does not survive a pod restart). Year-scoped
    # sources (TSE — params.year) only resume the files of their own
    # election year: two years share the bronze partition ``dt=<run>``,
    # and resuming the other year's files would re-append them to the
    # silver while the normalize delete is scoped to this run's year
    # (2024 rows doubled by the 2022 run of 2026-08-21).
    existing: dict[str, str] = {}
    try:
        existing = {
            key.rsplit("/", 1)[-1]: key
            for key in lake.list_bronze_files(source_name, run_date)
        }
    except Exception as exc:
        logger.warning(
            "Failed to list %s bronze files; downloading everything: %s",
            source_name,
            exc,
        )
    year = source.params.get("year")
    if year is not None:
        suffix = f"_{year}.zip"
        existing = {n: k for n, k in existing.items() if n.endswith(suffix)}

    manifest: list[dict[str, Any]] = [
        {"file": name, "bytes": None, "sha256": None, "lake_key": key}
        for name, key in sorted(existing.items())
    ]
    if existing:
        logger.info(
            "Resuming source '%s': %d files already in the bronze layer",
            source_name,
            len(existing),
        )

    with tempfile.TemporaryDirectory() as tmp:

        def _upload(path: Path) -> None:
            data = path.read_bytes()
            try:
                key = lake.write_bronze_file(
                    source_name, path.name, data, run_date=run_date
                )
            except Exception as exc:
                logger.warning(
                    "Failed to upload %s to the bronze layer: %s", path.name, exc
                )
                return
            manifest.append(
                {
                    "file": path.name,
                    "bytes": len(data),
                    "sha256": hashlib.sha256(data).hexdigest(),
                    "lake_key": key,
                }
            )
            path.unlink()

        params = {"files": source.params.get("files"), **source.params}
        download(
            Path(tmp),
            reference_month,
            skip=set(existing),
            on_file=_upload,
            **params,
        )

    if not manifest:
        raise RuntimeError(
            f"No files downloaded for source '{source_name}' (reference month {reference_month})"
        )

    payload = {"reference_month": reference_month, "files": manifest}
    try:
        lake.write_bronze(source_name, payload, run_date=run_date)
        lake.write_bronze_table(source_name, payload, run_date=run_date)
    except Exception as e:
        logger.warning(
            "Failed to write %s manifest to the bronze layer: %s", source_name, e
        )

    context["ti"].xcom_push(key=f"manifest_{source_name}", value=payload)
    return payload


def task_normalize_dump(
    source_name: str, spec_path: str, **context: Any
) -> dict[str, Any]:
    """Task: parse a dump source's bronze files into the silver entity tables.

    Streaming counterpart of the runner's ``normalize_<source>`` step of the
    file_dump formula: the download tempdir is gone in another worker, so
    the bronze files of the manifest are read back, parsed in chunks and
    appended to the silver tables chunk by chunk. The partition day of each
    entity in the manifest is deleted before parsing (Trino, cluster only),
    so a retried run re-parses from scratch without duplicating rows.
    Non-entity files (Cnaes.zip etc.) are skipped; sources without a
    registered dump parser or specs without the lake_silver/arangodb_graph
    destinations are a no-op.

    Args:
        source_name: Name of the dump source to normalize.
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Summary with per-entity row counts and parse/write errors.
    """
    import tempfile
    from pathlib import Path

    run_date = _lake_run_date(context) or date.today()
    spec = _load_spec(spec_path)
    ti = context["ti"]

    dump_parser = DUMP_PARSER_REGISTRY.get(source_name)
    destination_names = {d.name for d in spec.destinations}
    if dump_parser is None or not destination_names & {
        "lake_silver",
        "arangodb_graph",
    }:
        summary: dict[str, Any] = {
            "source": source_name,
            "entities": {},
            "skipped": True,
        }
        ti.xcom_push(key=f"entities_{source_name}", value=summary)
        return summary

    manifest = (
        ti.xcom_pull(task_ids=f"download_{source_name}", key=f"manifest_{source_name}")
        or {}
    )

    # Idempotency: a retry re-parses the whole dump from scratch, so the
    # partition day of every entity in the manifest is deleted first —
    # otherwise a pod restart mid-dump duplicates the rows already appended
    # (OOMKill loop of 2026-08-20). A delete failure aborts before any
    # append, so rows are never duplicated. Multi-year sources (TSE —
    # params.year) scope the delete to the election year, so two years
    # sharing a partition day never delete each other's rows; sources
    # without a year keep the whole-partition delete.
    source = next((s for s in spec.sources if s.name == source_name), None)
    election_year = source.params.get("year") if source is not None else None
    entities = {
        entity
        for entry in manifest.get("files", [])
        if (entity := dump_parser.entity_for_file(entry["file"])) is not None
    }
    if election_year is None:
        # The resolver of a year-aware source defaults to TSE_ELECTION_YEAR
        # when the spec omits params.year; mirror that default here so the
        # delete scope never diverges from the resolved dump.
        has_year_column = any(
            "election_year" in {f.name for f in lake.ENTITY_TABLES[e][0].fields}
            for e in entities
        )
        if has_year_column:
            election_year = TSE_ELECTION_YEAR
    for entity in sorted(entities):
        lake.delete_silver_entities_partition(
            entity, run_date, election_year=election_year
        )

    counts: dict[str, int] = {}
    errors = 0
    with tempfile.TemporaryDirectory() as tmp:
        for entry in manifest.get("files", []):
            filename = entry["file"]
            if dump_parser.entity_for_file(filename) is None:
                logger.info("Skipping non-entity dump file: %s", filename)
                continue
            try:
                data = lake.read_bronze_file(entry["lake_key"])
            except Exception as exc:
                errors += 1
                logger.warning("Failed to read bronze file %s: %s", filename, exc)
                continue
            zip_path = Path(tmp) / filename
            zip_path.write_bytes(data)
            for entity, records, parse_errors in dump_parser.parse(zip_path):
                errors += parse_errors
                if not records:
                    continue
                try:
                    lake.write_silver_entities(entity, records, run_date=run_date)
                    counts[entity] = counts.get(entity, 0) + len(records)
                except Exception as exc:
                    errors += 1
                    logger.warning(
                        "Failed to write %s chunk to the silver layer: %s", entity, exc
                    )

    summary = {"source": source_name, "entities": counts, "errors": errors}
    ti.xcom_push(key=f"entities_{source_name}", value=summary)
    logger.info("Dump normalization finished for %s: %s", source_name, summary)
    return summary


def task_normalize_pipeline(spec_path: str, **context: Any) -> list[dict[str, Any]]:
    """Task: normalize all crawled raw records into the unified schema.

    Pulls ``raw_<source>`` from upstream crawl tasks and pushes the normalized
    contracts to XCom under ``normalized_contracts``.

    Args:
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        List of serializable normalized contracts.
    """
    ti = context["ti"]
    spec = _load_spec(spec_path)

    contracts: list[dict[str, Any]] = []
    errors = 0
    for source in spec.sources:
        raw_records = (
            ti.xcom_pull(task_ids=f"crawl_{source.name}", key=f"raw_{source.name}")
            or []
        )
        normalizer = NORMALIZER_REGISTRY.get(source.name)
        if normalizer is None:
            raise ValueError(f"Source '{source.name}' has no registered normalizer")
        for raw in raw_records:
            try:
                contracts.append(normalizer(raw).model_dump(mode="json"))
            except Exception as exc:
                errors += 1
                logger.warning("Failed to normalize %s record: %s", source.name, exc)

    try:
        lake.write_silver(contracts, run_date=_lake_run_date(context))
    except Exception as e:
        logger.warning("Failed to write contracts to the silver layer: %s", e)

    ti.xcom_push(key="normalized_contracts", value=contracts)
    ti.xcom_push(key="normalization_errors", value=errors)
    return contracts


def _record_quality_batch(
    pipeline_name: str,
    contracts: list[dict[str, Any]],
    report: dict[str, Any],
) -> None:
    """Feeds the continuous quality monitor with the validated batch.

    Profiles the batch (registering it as the monitor baseline and checking
    the thresholds) and records the batch metrics — total, duplicates,
    normalization errors and quality-rule failures per severity — so the
    notification scheduler can report real numbers. Best-effort: any
    failure (missing Redis included) is logged and swallowed; validation
    never depends on the monitor.
    """
    from capiba.quality.monitor import QualityMonitor
    from capiba.quality.profiling import profile_dataset

    try:
        dataset = f"pipeline:{pipeline_name}"
        monitor = QualityMonitor()
        if contracts:
            df = pd.json_normalize(contracts, sep="_")
            profile = profile_dataset(df, dataset)
            monitor.register_baseline(dataset, profile)
            monitor.check(dataset, profile)

        failures: dict[str, int] = {}
        for rule in report.get("quality_rules") or []:
            if "error" in rule or rule.get("violations", 0) > 0:
                severity = rule.get("severity", "unknown")
                failures[severity] = failures.get(severity, 0) + 1

        monitor.record_batch(
            dataset,
            {
                "total": report.get("total", 0),
                "duplicates": report.get("duplicates", 0),
                "normalization_errors": report.get("normalization_errors", 0),
                "quality_rule_failures": failures,
            },
        )
    except Exception as exc:
        logger.warning(
            "Failed to record quality metrics for %s: %s", pipeline_name, exc
        )


def task_validate_pipeline(spec_path: str, **context: Any) -> dict[str, Any]:
    """Task: validate normalized contracts.

    Args:
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Validation report.
    """
    ti = context["ti"]
    spec = _load_spec(spec_path)

    contracts = ti.xcom_pull(task_ids="normalize", key="normalized_contracts") or []
    normalization_errors = (
        ti.xcom_pull(task_ids="normalize", key="normalization_errors") or 0
    )

    report = validate_contracts(contracts, normalization_errors=normalization_errors)

    if spec.validation:
        # Import here to avoid circular imports and keep registry populated.
        from capiba.pipeline.runner import _apply_ruleset

        try:
            quality = _apply_ruleset(spec.validation.ruleset, contracts)
            report["quality_rules"] = quality
        except Exception as exc:
            logger.warning("Failed to apply quality ruleset: %s", exc)

    # Best-effort: alerts never fail the task.
    notify_validation_failure(report, spec.name)
    # Best-effort: feed the continuous quality monitor (no-op without Redis).
    _record_quality_batch(spec.name, contracts, report)

    ti.xcom_push(key="validation_report", value=report)
    return report


def task_destination(
    destination_name: str, spec_path: str, **context: Any
) -> dict[str, Any]:
    """Task: run a single destination handler from the pipeline spec.

    Args:
        destination_name: Name of the destination to execute.
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Destination handler summary.
    """
    run_date = _lake_run_date(context) or date.today()
    spec = _load_spec(spec_path)
    handler = DESTINATION_REGISTRY.get(destination_name)
    if handler is None:
        raise ValueError(f"Unknown destination '{destination_name}'")

    ti = context["ti"]

    # file_dump specs load the graph from the silver entity tables and the
    # silver destination only reports the streaming normalize counts (the
    # writes already happened in the normalize_<source> task).
    if spec.formula == "file_dump":
        if destination_name == "arangodb_graph":
            return persist_cnpj_entities(execution_date=run_date.isoformat())
        if destination_name == "lake_silver":
            entities: dict[str, Any] = {}
            for source in spec.sources:
                value = ti.xcom_pull(
                    task_ids=f"normalize_{source.name}", key=f"entities_{source.name}"
                )
                if value is not None:
                    entities[source.name] = value
            return {"entities": entities}

    raw: dict[str, Any] = {}
    for source in spec.sources:
        if destination_name == "lake_bronze":
            if spec.formula == "file_dump":
                value = ti.xcom_pull(
                    task_ids=f"download_{source.name}", key=f"manifest_{source.name}"
                )
            elif spec.formula == "documents_collect":
                # Records enriched with ``text_bronze_file`` by the
                # download_<source>_texts task.
                value = ti.xcom_pull(
                    task_ids=f"download_{source.name}_texts",
                    key=f"raw_{source.name}",
                )
            elif spec.formula == "terms_collect":
                # Records enriched with ``terms_bronze_file`` by the
                # persist_<source>_terms task.
                value = ti.xcom_pull(
                    task_ids=f"persist_{source.name}_terms",
                    key=f"raw_{source.name}",
                )
            else:
                value = ti.xcom_pull(
                    task_ids=f"crawl_{source.name}", key=f"raw_{source.name}"
                )
            if value is not None:
                raw[source.name] = value

    contracts = ti.xcom_pull(task_ids="normalize", key="normalized_contracts") or []

    from capiba.pipeline.runner import FormulaResult

    result = FormulaResult(raw=raw, contracts=contracts, manifests=raw)
    summary = handler(spec, run_date, result)
    return summary  # type: ignore[no-any-return]


def task_post_step(
    step_name: str,
    spec_path: str,
    select: list[str] | None = None,
    **context: Any,
) -> dict[str, Any]:
    """Task: run a single post step declared in the pipeline spec.

    Post steps are skipped on backfill runs (``run_type == "backfill"``):
    ``dbt_run`` and ``detect`` reprocess the whole silver/gold tables, so
    running them per backfilled day is O(n²) work and memory-heavy
    (OOMKills observed in the 2026-08-19 backfill). A final regular run
    after the backfill rebuilds the marts and signals over the
    accumulated data.

    Args:
        step_name: Name of the post step (``dbt_run`` or ``detect``).
        spec_path: Path of the YAML pipeline spec.
        select: Optional dbt model selection for ``dbt_run`` (ignored by
            other post steps).
        context: Airflow context.

    Returns:
        Post-step summary.

    Raises:
        AirflowSkipException: On backfill runs (post steps are deferred
            to the final regular run).
    """
    dag_run = context.get("dag_run")
    run_type = getattr(dag_run, "run_type", None)
    if str(getattr(run_type, "value", run_type)) == "backfill":
        from airflow.exceptions import AirflowSkipException

        raise AirflowSkipException(f"Post step '{step_name}' skipped on backfill run")
    if step_name == "dbt_run":
        return task_dbt_run(select=select, **context)
    if step_name == "detect":
        return task_detect(**context)
    raise ValueError(f"Unknown post step '{step_name}'")


def task_gold_report(spec_path: str, **context: Any) -> dict[str, Any]:
    """Task: publish the run report to the gold layer.

    Args:
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Summary with the report key.
    """
    from capiba.pipeline.runner import PipelineReport

    run_date = _lake_run_date(context) or date.today()
    spec = _load_spec(spec_path)
    ti = context["ti"]

    report = PipelineReport(
        pipeline=spec.name,
        execution_date=run_date,
        started_at=datetime.now(UTC),
        duration_seconds=0.0,
        success=True,
        validation=ti.xcom_pull(task_ids="validate", key="validation_report") or None,
    )
    key = lake.write_gold(
        report.model_dump(mode="json"),
        report_name=spec.name,
        run_date=run_date,
    )
    return {"key": key}


# Marts that read the TSE silvers (campaign_donations/candidacies). Full
# runs exclude them until the first monthly_tse load lands — the mart SQL
# fails with TABLE_NOT_FOUND otherwise and would block the whole
# gold_detection DAG.
_TSE_SILVER_ENTITIES = ("campaign_donations", "candidacies")
_TSE_DEPENDENT_MARTS = ["political_connections"]
# Marts refreshed by the hourly pipeline's own dbt_run (--select). The
# daily full run excludes them: two concurrent dbt invocations committing
# the same Iceberg table are rejected by Lakekeeper ("Failed to commit
# the transaction during insert: Cannot assign a new UUID" — gold run of
# 2026-08-21 collided with the hourly 07:07 run).
_HOURLY_OWNED_MARTS = ["pod_usage_hourly", "platform_cost_daily"]


def task_dbt_run(select: list[str] | None = None, **context: Any) -> dict[str, Any]:
    """Task: build the gold Iceberg marts with dbt.

    Reads the silver ``contracts`` table through the Iceberg REST catalog
    and materializes the analytical marts in the gold warehouse.

    Args:
        select: Optional dbt model selection (``--select``); None builds
            the whole project (used by ``gold_detection``), excluding the
            hourly-owned marts (``_HOURLY_OWNED_MARTS`` — refreshed by the
            hourly pipeline itself) and the TSE-dependent marts while the
            TSE silver tables do not exist.
        context: Airflow context.

    Returns:
        Execution summary (command, selection, exclusion and project dir).
    """
    from capiba.pipeline.dbt_runner import run_dbt

    exclude: list[str] = []
    if select is None:
        exclude = list(_HOURLY_OWNED_MARTS)
        if any(
            not lake.silver_table_exists(entity) for entity in _TSE_SILVER_ENTITIES
        ):
            exclude += _TSE_DEPENDENT_MARTS
            logger.warning(
                "TSE silver tables missing; excluding %s from the full dbt run",
                _TSE_DEPENDENT_MARTS,
            )
    logger.info("Building gold marts with dbt (select: %s, exclude: %s)",
                select or "all", exclude or "none")
    run_dbt("run", select=select, exclude=exclude or None)
    return {
        "dbt": "run",
        "select": select or [],
        "exclude": exclude,
        "project_dir": DBT_PROJECT_DIR,
    }


def task_run_pipeline(spec_path: str, **context: Any) -> dict[str, Any]:
    """Task: run a declarative (YAML) ingestion pipeline.

    Loads the pipeline spec, resolves the run date from the Airflow context
    and executes the pipeline through ``capiba.pipeline.runner`` (the run
    report is published to the gold layer when the spec declares the
    ``gold_report`` destination). Post steps declared in the spec
    (``dbt_run``, ``detect``) run after the pipeline, reusing the existing
    task functions.

    Args:
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Execution summary (pipeline name, success, step count, post steps).
    """
    from capiba.pipeline.runner import run_pipeline
    from capiba.pipeline.spec import load_spec

    run_date = _lake_run_date(context) or date.today()
    spec = load_spec(spec_path)
    logger.info("Running declarative pipeline '%s' for %s", spec.name, run_date)

    report = run_pipeline(spec, run_date)

    post_results: dict[str, Any] = {}
    for step in spec.post_steps:
        if step.name == "dbt_run":
            post_results["dbt_run"] = task_dbt_run(
                select=step.select or None, **context
            )
        elif step.name == "detect":
            post_results["detect"] = task_detect(**context)

    return {
        "pipeline": report.pipeline,
        "success": report.success,
        "steps": len(report.steps),
        "post_steps": post_results,
    }
