"""Atomic transformation tasks.

Responsibility: pure functions (``validate_contracts``, ``persist_contracts``)
implementing steps of the ingestion pipeline, with no Airflow dependency,
reused by ``capiba.pipeline.runner``. The ``task_*`` wrappers adapt the
declarative pipeline steps to the Airflow context (XCom, ``ds``) and are
called by the DAG operators generated by ``dags/pipeline_factory.py`` from
``dags/pipelines/*.yaml``; ``scripts/ingestion.py`` executes the same specs
through the runner, without Airflow.

``task_run_pipeline`` is the entrypoint of the declarative framework: the
DAGs call it with the spec path, delegating execution to
``capiba.pipeline.runner``.
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, date, datetime
from typing import Any

import pandas as pd

from capiba.config import DBT_PROJECT_DIR, DETECTION_COLLUSION_MIN_WINS
from capiba.db.arangodb import get_capiba_db
from capiba.db.triage import register_signals
from capiba.detection.graphs import detect_collusion
from capiba.detection.screening import sanctioned_supplier_signals
from capiba.detection.signals import (
    SignalType,
    anomalous_price,
    collusion_signals,
    is_non_competitive,
    single_bid_score,
)
from capiba.detection.statistical import (
    duration_outlier,
    hhi_index,
)
from capiba.evidence.packages import store_signal_packages
from capiba.evidence.storage import EvidenceStorage
from capiba.ingestion.normalizer import Contract
from capiba.ingestion.persistence import bulk_upsert_cnpj, bulk_upsert_contracts
from capiba.ingestion.validator import checksum, detect_duplicates
from capiba.notification.alerts import notify_fraud_signals, notify_validation_failure
from capiba.pipeline import lake
from capiba.pipeline.registry import (
    DESTINATION_REGISTRY,
    DUMP_PARSER_REGISTRY,
    NORMALIZER_REGISTRY,
    SOURCE_REGISTRY,
)
from capiba.pipeline.window import resolve_window
from capiba.quality.lineage import LineageTracker

logger = logging.getLogger(__name__)


def _lake_run_date(context: dict[str, Any]) -> date | None:
    """Extracts the run date from the Airflow context.

    Airflow 3 removed ``ds`` from the task context: use ``logical_date``
    (falling back to the DAG run's ``run_after``, which manual runs set),
    and still accept the legacy ``ds`` key for offline callers and tests.
    """
    run_dt = context.get("logical_date")
    if run_dt is None:
        dag_run = context.get("dag_run")
        run_dt = getattr(dag_run, "run_after", None)
    if isinstance(run_dt, datetime):
        return run_dt.date()
    if run_dt is not None:
        return date.fromisoformat(str(run_dt)[:10])
    ds = context.get("ds")
    return date.fromisoformat(ds) if ds else None


def validate_contracts(
    contracts: list[dict[str, Any]],
    normalization_errors: int = 0,
) -> dict[str, Any]:
    """Validates normalized contracts (checksum and duplicates).

    Args:
        contracts: Serializable normalized contracts.
        normalization_errors: Errors recorded in the normalization step.

    Returns:
        Validation report.
    """
    logger.info("Validating %d contracts", len(contracts))

    raw_bytes = json.dumps(contracts, sort_keys=True).encode()
    chk = checksum(raw_bytes)
    duplicates = detect_duplicates(contracts, key="id")

    report = {
        "total": len(contracts),
        "checksum": chk,
        "duplicates": len(duplicates),
        "duplicate_ids": duplicates,
        "normalization_errors": normalization_errors,
        "valid": len(duplicates) == 0,
    }

    logger.info("Validation: %s", report)
    return report


def persist_contracts(
    contracts_dict: list[dict[str, Any]],
    execution_date: str | None = None,
) -> dict[str, Any]:
    """Persists validated contracts in ArangoDB, recording lineage.

    Args:
        contracts_dict: Serializable normalized contracts.
        execution_date: Execution date (lineage metadata).

    Returns:
        Persistence summary.
    """
    logger.info("Persisting %d contracts", len(contracts_dict))

    tracker = LineageTracker()
    source_id = tracker.register_source(
        name="daily_ingestion",
        url="https://pncp.gov.br/api/consulta",
        api_type="REST",
        metadata={"execution_date": execution_date},
    )

    contracts = []
    for c in contracts_dict:
        try:
            contracts.append(Contract.model_validate(c))
        except Exception as e:
            logger.warning("Failed to revalidate contract for persistence: %s", e)

    try:
        db = get_capiba_db()
        summary = bulk_upsert_contracts(db, contracts, tracker=tracker)
        summary["lineage"] = tracker.export()
        summary["source_id"] = source_id
    except Exception as e:
        logger.error("Persistence failed: %s", e)
        summary = {"error": str(e)}

    return summary


def persist_cnpj_entities(execution_date: str | None = None) -> dict[str, Any]:
    """Persists the silver CNPJ entities in the ArangoDB graph, in batches.

    Reads the silver ``companies``/``partners`` tables batch by batch and
    bulk-upserts the graph vertices and ``partner_of`` edges, so the large
    dump tables never materialize in memory.

    Args:
        execution_date: Execution date (metadata only).

    Returns:
        Persistence summary ``{companies, partners, edges, errors}``
        (or ``{"error": ...}`` on failure).
    """
    totals = {"companies": 0, "partners": 0, "edges": 0, "errors": 0}
    try:
        db = get_capiba_db()
        for entity in ("companies", "partners"):
            for batch in lake.read_silver_entities(entity):
                summary = bulk_upsert_cnpj(
                    db,
                    companies=batch if entity == "companies" else [],
                    partners=batch if entity == "partners" else [],
                )
                for key in totals:
                    totals[key] += summary[key]
    except Exception as e:
        logger.error("CNPJ persistence failed: %s", e)
        return {"error": str(e), **totals}

    logger.info("CNPJ graph load finished: %s", totals)
    return totals


def detect_fraud_signals(contracts: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Computes statistical fraud signals over the silver contracts.

    Signals (canonical vocabulary of ``capiba.detection.signals.SignalType``;
    score semantics: higher = more suspicious):

    - ``anomalous_price`` per supplier: composite of the Benford deviation
      (>= 10 positive amounts) and the IsolationForest anomaly rate over
      (log amount, duration) (>= 15 contracts); the score is the max of the
      eligible components, both preserved in ``details`` (null when a
      component is ineligible).
    - ``single_bid`` per supplier: rate of contracts in non-competitive
      modality (dispensa/inexigibilidade); emitted only when the rate is
      positive and the supplier has >= 3 contracts.
    - ``concentration`` per buyer: HHI of the supplier market shares;
      requires >= 3 contracts.
    - ``anomalous_duration`` per supplier: share of contracts whose validity
      duration is a pooled IQR outlier; emitted only when the share > 0.

    Args:
        contracts: Silver contract rows (nested ``buyer``/``supplier``).

    Returns:
        Signal rows (entity_type, entity_id, signal_type, score, details).
    """
    if not contracts:
        return []

    def _party_id(party: Any, key: str) -> Any:
        return party.get(key) if isinstance(party, dict) else None

    df = pd.DataFrame(contracts)
    df["buyer_id"] = df["buyer"].map(lambda b: _party_id(b, "siafi_code"))
    df["supplier_id"] = df["supplier"].map(
        lambda s: _party_id(s, "cnpj") or _party_id(s, "cpf")
    )
    df["amount_float"] = pd.to_numeric(df["amount"], errors="coerce")
    df["duration_days"] = (
        pd.to_datetime(df["validity_end"], errors="coerce")
        - pd.to_datetime(df["validity_start"], errors="coerce")
    ).dt.days
    if "modality" not in df.columns:
        df["modality"] = None

    signals: list[dict[str, Any]] = []

    for supplier_id, group in df.dropna(subset=["supplier_id"]).groupby("supplier_id"):
        composite = anomalous_price(group["amount_float"], group["duration_days"])
        if composite is not None:
            score, components = composite
            signals.append(
                {
                    "entity_type": "supplier",
                    "entity_id": str(supplier_id),
                    "signal_type": SignalType.ANOMALOUS_PRICE,
                    "score": score,
                    "details": json.dumps({**components, "contracts": int(len(group))}),
                }
            )

        non_competitive = int(group["modality"].map(is_non_competitive).sum())
        rate = single_bid_score(group["modality"])
        if rate > 0 and len(group) >= 3:
            signals.append(
                {
                    "entity_type": "supplier",
                    "entity_id": str(supplier_id),
                    "signal_type": SignalType.SINGLE_BID,
                    "score": rate,
                    "details": json.dumps(
                        {
                            "contracts": int(len(group)),
                            "non_competitive": non_competitive,
                        }
                    ),
                }
            )

    hhi_df = df[["buyer_id", "supplier_id", "amount_float"]].rename(
        columns={"amount_float": "amount"}
    )
    for buyer_id, group in df.dropna(subset=["buyer_id"]).groupby("buyer_id"):
        if len(group) >= 3:
            hhi = hhi_index(str(buyer_id), hhi_df)
            signals.append(
                {
                    "entity_type": "buyer",
                    "entity_id": str(buyer_id),
                    "signal_type": SignalType.CONCENTRATION,
                    "score": hhi,
                    "details": json.dumps(
                        {
                            "contracts": len(group),
                            "suppliers": int(group["supplier_id"].nunique()),
                        }
                    ),
                }
            )

    with_durations = df.dropna(subset=["duration_days"])
    if len(with_durations) >= 3:
        outliers = duration_outlier(with_durations)
        flagged = with_durations[outliers]
        for supplier_id, group in with_durations.dropna(subset=["supplier_id"]).groupby(
            "supplier_id"
        ):
            share = len(flagged[flagged["supplier_id"] == supplier_id]) / len(group)
            if share > 0:
                signals.append(
                    {
                        "entity_type": "supplier",
                        "entity_id": str(supplier_id),
                        "signal_type": SignalType.ANOMALOUS_DURATION,
                        "score": round(float(share), 4),
                        "details": json.dumps({"contracts": len(group)}),
                    }
                )

    logger.info("Fraud signals computed: %d", len(signals))
    return signals


def task_detect(**context: Any) -> dict[str, Any]:
    """Task: compute fraud signals over the silver contracts (gold table).

    Args:
        context: Airflow context.

    Returns:
        Detection summary (number of signals written).
    """
    run_date = _lake_run_date(context)

    try:
        contracts = lake.read_silver_contracts()
    except Exception as e:
        logger.warning("Failed to read the silver contracts table: %s", e)
        contracts = []

    signals = detect_fraud_signals(contracts)

    # Best-effort: sanction screening (O3) never fails the task (the silver
    # sanctions table may not exist yet).
    try:
        sanctions = [
            row for batch in lake.read_silver_entities("sanctions") for row in batch
        ]
        signals.extend(sanctioned_supplier_signals(contracts, sanctions))
    except Exception as e:
        logger.warning("Sanction screening unavailable (silver sanctions): %s", e)

    # Best-effort: graph signals never fail the task (ArangoDB may be down).
    try:
        db = get_capiba_db()
        pairs = detect_collusion(db, min_wins=DETECTION_COLLUSION_MIN_WINS)
        signals.extend(collusion_signals(pairs, DETECTION_COLLUSION_MIN_WINS))
        # Editorial triage queue (O10): new signals enter as pending_review.
        register_signals(db, signals)
    except Exception as e:
        logger.warning("Collusion detection unavailable (ArangoDB): %s", e)

    try:
        if signals:
            lake.write_fraud_signals(signals, run_date=run_date)
    except Exception as e:
        logger.warning("Failed to write fraud signals to the gold layer: %s", e)

    # Best-effort: reproducible evidence packages (O9) never fail the task.
    try:
        if signals:
            store_signal_packages(EvidenceStorage(), signals, contracts, run_date)
    except Exception as e:
        logger.warning("Failed to store signal evidence packages (MinIO): %s", e)

    # Best-effort: alerts never fail the task.
    notify_fraud_signals(signals, run_date)

    return {"signals": len(signals)}


def _load_spec(spec_path: str) -> Any:
    """Loads a pipeline spec, populating formula/destination registries."""
    from capiba.pipeline.spec import load_spec

    return load_spec(spec_path)


def task_crawl_source(
    source_name: str, spec_path: str, **context: Any
) -> list[dict[str, Any]]:
    """Task: crawl a single source declared in the pipeline spec.

    The raw records are pushed to XCom under ``raw_<source_name>`` so later
    tasks (normalize, bronze destinations) can consume them.

    Args:
        source_name: Name of the source to crawl (must exist in the spec).
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        List of raw records.
    """
    run_date = _lake_run_date(context) or date.today()
    spec = _load_spec(spec_path)
    source = next((s for s in spec.sources if s.name == source_name), None)
    if source is None:
        raise ValueError(f"Source '{source_name}' not found in spec '{spec_path}'")

    date_range = resolve_window(source.window or spec.window, run_date)
    fetch = SOURCE_REGISTRY[source_name].fetch
    if fetch is None:
        raise ValueError(f"Source '{source_name}' has no record fetcher")

    logger.info("Crawling source '%s' for %s", source_name, run_date)
    records = fetch(date_range.start, date_range.end, **source.params)

    try:
        lake.write_bronze(source_name, records, run_date=run_date)
        lake.write_bronze_table(source_name, records, run_date=run_date)
    except Exception as e:
        logger.warning("Failed to write %s payload to the bronze layer: %s", source_name, e)

    context["ti"].xcom_push(key=f"raw_{source_name}", value=records)
    return records


def task_download_source(
    source_name: str, spec_path: str, **context: Any
) -> dict[str, Any]:
    """Task: download a dump source declared in the pipeline spec.

    Each downloaded file is uploaded to the bronze layer immediately
    (and removed from the tempdir); on a retry, files already present in
    the bronze layer for the run date are skipped and re-entered into the
    manifest, so a pod restart no longer restarts a multi-GB dump from
    scratch. The manifest is pushed to XCom under ``manifest_<source_name>``.

    Args:
        source_name: Name of the dump source to download.
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Manifest payload (reference month and file list).
    """
    import hashlib
    import tempfile
    from pathlib import Path

    run_date = _lake_run_date(context) or date.today()
    spec = _load_spec(spec_path)
    source = next((s for s in spec.sources if s.name == source_name), None)
    if source is None:
        raise ValueError(f"Source '{source_name}' not found in spec '{spec_path}'")

    date_range = resolve_window(source.window or spec.window, run_date)
    if date_range.start is None:
        raise ValueError(f"Source '{source_name}' requires a bounded window")
    reference_month = date_range.start.strftime("%Y-%m")

    download = SOURCE_REGISTRY[source_name].download
    if download is None:
        raise ValueError(f"Source '{source_name}' has no dump downloader")

    logger.info("Downloading source '%s' for %s", source_name, reference_month)

    # Resume support: files already uploaded to the bronze layer by a
    # previous attempt are skipped and re-entered into the manifest (the
    # download tempdir does not survive a pod restart).
    existing: dict[str, str] = {}
    try:
        existing = {
            key.rsplit("/", 1)[-1]: key
            for key in lake.list_bronze_files(source_name, run_date)
        }
    except Exception as exc:
        logger.warning(
            "Failed to list %s bronze files; downloading everything: %s",
            source_name,
            exc,
        )

    manifest: list[dict[str, Any]] = [
        {"file": name, "bytes": None, "sha256": None, "lake_key": key}
        for name, key in sorted(existing.items())
    ]
    if existing:
        logger.info(
            "Resuming source '%s': %d files already in the bronze layer",
            source_name,
            len(existing),
        )

    with tempfile.TemporaryDirectory() as tmp:
        def _upload(path: Path) -> None:
            data = path.read_bytes()
            try:
                key = lake.write_bronze_file(
                    source_name, path.name, data, run_date=run_date
                )
            except Exception as exc:
                logger.warning(
                    "Failed to upload %s to the bronze layer: %s", path.name, exc
                )
                return
            manifest.append(
                {
                    "file": path.name,
                    "bytes": len(data),
                    "sha256": hashlib.sha256(data).hexdigest(),
                    "lake_key": key,
                }
            )
            path.unlink()

        params = {"files": source.params.get("files"), **source.params}
        download(
            Path(tmp),
            reference_month,
            skip=set(existing),
            on_file=_upload,
            **params,
        )

    if not manifest:
        raise RuntimeError(
            f"No files downloaded for source '{source_name}' (reference month {reference_month})"
        )

    payload = {"reference_month": reference_month, "files": manifest}
    try:
        lake.write_bronze(source_name, payload, run_date=run_date)
        lake.write_bronze_table(source_name, payload, run_date=run_date)
    except Exception as e:
        logger.warning(
            "Failed to write %s manifest to the bronze layer: %s", source_name, e
        )

    context["ti"].xcom_push(key=f"manifest_{source_name}", value=payload)
    return payload


def task_normalize_dump(source_name: str, spec_path: str, **context: Any) -> dict[str, Any]:
    """Task: parse a dump source's bronze files into the silver entity tables.

    Streaming counterpart of the runner's ``normalize_<source>`` step of the
    file_dump formula: the download tempdir is gone in another worker, so
    the bronze files of the manifest are read back, parsed in chunks and
    appended to the silver tables chunk by chunk. Non-entity files
    (Cnaes.zip etc.) are skipped; sources without a registered dump parser
    or specs without the lake_silver/arangodb_graph destinations are a
    no-op.

    Args:
        source_name: Name of the dump source to normalize.
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Summary with per-entity row counts and parse/write errors.
    """
    import tempfile
    from pathlib import Path

    from capiba.ingestion.cnpj import entity_for_zip

    run_date = _lake_run_date(context) or date.today()
    spec = _load_spec(spec_path)
    ti = context["ti"]

    parser = DUMP_PARSER_REGISTRY.get(source_name)
    destination_names = {d.name for d in spec.destinations}
    if parser is None or not destination_names & {"lake_silver", "arangodb_graph"}:
        summary: dict[str, Any] = {"source": source_name, "entities": {}, "skipped": True}
        ti.xcom_push(key=f"entities_{source_name}", value=summary)
        return summary

    manifest = (
        ti.xcom_pull(task_ids=f"download_{source_name}", key=f"manifest_{source_name}")
        or {}
    )

    counts: dict[str, int] = {}
    errors = 0
    with tempfile.TemporaryDirectory() as tmp:
        for entry in manifest.get("files", []):
            filename = entry["file"]
            if entity_for_zip(filename) is None:
                logger.info("Skipping non-entity dump file: %s", filename)
                continue
            try:
                data = lake.read_bronze_file(entry["lake_key"])
            except Exception as exc:
                errors += 1
                logger.warning("Failed to read bronze file %s: %s", filename, exc)
                continue
            zip_path = Path(tmp) / filename
            zip_path.write_bytes(data)
            for entity, records, parse_errors in parser(zip_path):
                errors += parse_errors
                if not records:
                    continue
                try:
                    lake.write_silver_entities(entity, records, run_date=run_date)
                    counts[entity] = counts.get(entity, 0) + len(records)
                except Exception as exc:
                    errors += 1
                    logger.warning(
                        "Failed to write %s chunk to the silver layer: %s", entity, exc
                    )

    summary = {"source": source_name, "entities": counts, "errors": errors}
    ti.xcom_push(key=f"entities_{source_name}", value=summary)
    logger.info("Dump normalization finished for %s: %s", source_name, summary)
    return summary


def task_normalize_pipeline(spec_path: str, **context: Any) -> list[dict[str, Any]]:
    """Task: normalize all crawled raw records into the unified schema.

    Pulls ``raw_<source>`` from upstream crawl tasks and pushes the normalized
    contracts to XCom under ``normalized_contracts``.

    Args:
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        List of serializable normalized contracts.
    """
    ti = context["ti"]
    spec = _load_spec(spec_path)

    contracts: list[dict[str, Any]] = []
    errors = 0
    for source in spec.sources:
        raw_records = ti.xcom_pull(task_ids=f"crawl_{source.name}", key=f"raw_{source.name}") or []
        normalizer = NORMALIZER_REGISTRY.get(source.name)
        if normalizer is None:
            raise ValueError(f"Source '{source.name}' has no registered normalizer")
        for raw in raw_records:
            try:
                contracts.append(normalizer(raw).model_dump(mode="json"))
            except Exception as exc:
                errors += 1
                logger.warning("Failed to normalize %s record: %s", source.name, exc)

    try:
        lake.write_silver(contracts, run_date=_lake_run_date(context))
    except Exception as e:
        logger.warning("Failed to write contracts to the silver layer: %s", e)

    ti.xcom_push(key="normalized_contracts", value=contracts)
    ti.xcom_push(key="normalization_errors", value=errors)
    return contracts


def _record_quality_batch(
    pipeline_name: str,
    contracts: list[dict[str, Any]],
    report: dict[str, Any],
) -> None:
    """Feeds the continuous quality monitor with the validated batch.

    Profiles the batch (registering it as the monitor baseline and checking
    the thresholds) and records the batch metrics — total, duplicates,
    normalization errors and quality-rule failures per severity — so the
    notification scheduler can report real numbers. Best-effort: any
    failure (missing Redis included) is logged and swallowed; validation
    never depends on the monitor.
    """
    from capiba.quality.monitor import QualityMonitor
    from capiba.quality.profiling import profile_dataset

    try:
        dataset = f"pipeline:{pipeline_name}"
        monitor = QualityMonitor()
        if contracts:
            df = pd.json_normalize(contracts, sep="_")
            profile = profile_dataset(df, dataset)
            monitor.register_baseline(dataset, profile)
            monitor.check(dataset, profile)

        failures: dict[str, int] = {}
        for rule in report.get("quality_rules") or []:
            if "error" in rule or rule.get("violations", 0) > 0:
                severity = rule.get("severity", "unknown")
                failures[severity] = failures.get(severity, 0) + 1

        monitor.record_batch(
            dataset,
            {
                "total": report.get("total", 0),
                "duplicates": report.get("duplicates", 0),
                "normalization_errors": report.get("normalization_errors", 0),
                "quality_rule_failures": failures,
            },
        )
    except Exception as exc:
        logger.warning("Failed to record quality metrics for %s: %s", pipeline_name, exc)


def task_validate_pipeline(spec_path: str, **context: Any) -> dict[str, Any]:
    """Task: validate normalized contracts.

    Args:
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Validation report.
    """
    ti = context["ti"]
    spec = _load_spec(spec_path)

    contracts = ti.xcom_pull(task_ids="normalize", key="normalized_contracts") or []
    normalization_errors = ti.xcom_pull(task_ids="normalize", key="normalization_errors") or 0

    report = validate_contracts(contracts, normalization_errors=normalization_errors)

    if spec.validation:
        # Import here to avoid circular imports and keep registry populated.
        from capiba.pipeline.runner import _apply_ruleset

        try:
            quality = _apply_ruleset(spec.validation.ruleset, contracts)
            report["quality_rules"] = quality
        except Exception as exc:
            logger.warning("Failed to apply quality ruleset: %s", exc)

    # Best-effort: alerts never fail the task.
    notify_validation_failure(report, spec.name)
    # Best-effort: feed the continuous quality monitor (no-op without Redis).
    _record_quality_batch(spec.name, contracts, report)

    ti.xcom_push(key="validation_report", value=report)
    return report


def task_destination(
    destination_name: str, spec_path: str, **context: Any
) -> dict[str, Any]:
    """Task: run a single destination handler from the pipeline spec.

    Args:
        destination_name: Name of the destination to execute.
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Destination handler summary.
    """
    run_date = _lake_run_date(context) or date.today()
    spec = _load_spec(spec_path)
    handler = DESTINATION_REGISTRY.get(destination_name)
    if handler is None:
        raise ValueError(f"Unknown destination '{destination_name}'")

    ti = context["ti"]

    # file_dump specs load the graph from the silver entity tables and the
    # silver destination only reports the streaming normalize counts (the
    # writes already happened in the normalize_<source> task).
    if spec.formula == "file_dump":
        if destination_name == "arangodb_graph":
            return persist_cnpj_entities(execution_date=run_date.isoformat())
        if destination_name == "lake_silver":
            entities: dict[str, Any] = {}
            for source in spec.sources:
                value = ti.xcom_pull(
                    task_ids=f"normalize_{source.name}", key=f"entities_{source.name}"
                )
                if value is not None:
                    entities[source.name] = value
            return {"entities": entities}

    raw: dict[str, Any] = {}
    for source in spec.sources:
        if destination_name == "lake_bronze":
            if spec.formula == "file_dump":
                value = ti.xcom_pull(task_ids=f"download_{source.name}", key=f"manifest_{source.name}")
            else:
                value = ti.xcom_pull(task_ids=f"crawl_{source.name}", key=f"raw_{source.name}")
            if value is not None:
                raw[source.name] = value

    contracts = ti.xcom_pull(task_ids="normalize", key="normalized_contracts") or []

    from capiba.pipeline.runner import FormulaResult

    result = FormulaResult(raw=raw, contracts=contracts, manifests=raw)
    summary = handler(spec, run_date, result)
    return summary  # type: ignore[no-any-return]


def task_post_step(step_name: str, spec_path: str, **context: Any) -> dict[str, Any]:
    """Task: run a single post step declared in the pipeline spec.

    Post steps are skipped on backfill runs (``run_type == "backfill"``):
    ``dbt_run`` and ``detect`` reprocess the whole silver/gold tables, so
    running them per backfilled day is O(n²) work and memory-heavy
    (OOMKills observed in the 2026-08-19 backfill). A final regular run
    after the backfill rebuilds the marts and signals over the
    accumulated data.

    Args:
        step_name: Name of the post step (``dbt_run`` or ``detect``).
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Post-step summary.

    Raises:
        AirflowSkipException: On backfill runs (post steps are deferred
            to the final regular run).
    """
    dag_run = context.get("dag_run")
    run_type = getattr(dag_run, "run_type", None)
    if str(getattr(run_type, "value", run_type)) == "backfill":
        from airflow.exceptions import AirflowSkipException

        raise AirflowSkipException(f"Post step '{step_name}' skipped on backfill run")
    if step_name == "dbt_run":
        return task_dbt_run(**context)
    if step_name == "detect":
        return task_detect(**context)
    raise ValueError(f"Unknown post step '{step_name}'")


def task_gold_report(spec_path: str, **context: Any) -> dict[str, Any]:
    """Task: publish the run report to the gold layer.

    Args:
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Summary with the report key.
    """
    from capiba.pipeline.runner import PipelineReport

    run_date = _lake_run_date(context) or date.today()
    spec = _load_spec(spec_path)
    ti = context["ti"]

    report = PipelineReport(
        pipeline=spec.name,
        execution_date=run_date,
        started_at=datetime.now(UTC),
        duration_seconds=0.0,
        success=True,
        validation=ti.xcom_pull(task_ids="validate", key="validation_report") or None,
    )
    key = lake.write_gold(
        report.model_dump(mode="json"),
        report_name=spec.name,
        run_date=run_date,
    )
    return {"key": key}


def task_dbt_run(**context: Any) -> dict[str, Any]:
    """Task: build the gold Iceberg marts with dbt.

    Reads the silver ``contracts`` table through the Iceberg REST catalog
    and materializes the analytical marts in the gold warehouse.

    Args:
        context: Airflow context.

    Returns:
        Execution summary (command and project dir).
    """
    from capiba.pipeline.dbt_runner import run_dbt

    logger.info("Building gold marts with dbt")
    run_dbt("run")
    return {"dbt": "run", "project_dir": DBT_PROJECT_DIR}


def task_run_pipeline(spec_path: str, **context: Any) -> dict[str, Any]:
    """Task: run a declarative (YAML) ingestion pipeline.

    Loads the pipeline spec, resolves the run date from the Airflow context
    and executes the pipeline through ``capiba.pipeline.runner`` (the run
    report is published to the gold layer when the spec declares the
    ``gold_report`` destination). Post steps declared in the spec
    (``dbt_run``, ``detect``) run after the pipeline, reusing the existing
    task functions.

    Args:
        spec_path: Path of the YAML pipeline spec.
        context: Airflow context.

    Returns:
        Execution summary (pipeline name, success, step count, post steps).
    """
    from capiba.pipeline.runner import run_pipeline
    from capiba.pipeline.spec import load_spec

    run_date = _lake_run_date(context) or date.today()
    spec = load_spec(spec_path)
    logger.info("Running declarative pipeline '%s' for %s", spec.name, run_date)

    report = run_pipeline(spec, run_date)

    post_results: dict[str, Any] = {}
    for step in spec.post_steps:
        if step == "dbt_run":
            post_results["dbt_run"] = task_dbt_run(**context)
        elif step == "detect":
            post_results["detect"] = task_detect(**context)

    return {
        "pipeline": report.pipeline,
        "success": report.success,
        "steps": len(report.steps),
        "post_steps": post_results,
    }
