{{- if and .Values.postgresql.enabled .Values.postgresql.persistence.enabled .Values.global.servicesDataPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "capiba.postgresql.fullname" . }}-data-pv
  labels:
    {{- include "capiba.labels" . | nindent 4 }}
    {{- include "capiba.componentLabels" (dict "component" "postgresql" "context" .) | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.postgresql.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  hostPath:
    path: {{ printf "%s/postgresql" .Values.global.servicesDataPath | quote }}
    type: DirectoryOrCreate
{{- end }}
