{{- if .Values.marquez.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capiba.marquez.fullname" . }}-secrets
  labels:
    {{- include "capiba.labels" . | nindent 4 }}
    {{- include "capiba.componentLabels" (dict "component" "marquez" "context" .) | nindent 4 }}
type: Opaque
stringData:
  # Rendered into config.yml by the Marquez image entrypoint
  POSTGRES_HOST: {{ include "capiba.postgresql.fullname" . | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.service.port | quote }}
  POSTGRES_DB: {{ .Values.marquez.database.dbname | quote }}
  POSTGRES_USER: {{ .Values.marquez.database.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.marquez.database.password | quote }}
{{- end }}
