{{- if and .Values.arangodb.enabled .Values.arangodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "capiba.arangodb.fullname" . }}-data
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "capiba.labels" . | nindent 4 }}
    {{- include "capiba.componentLabels" (dict "component" "arangodb" "context" .) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.servicesDataPath }}
  storageClassName: ""
  volumeName: {{ include "capiba.arangodb.fullname" . }}-data-pv
  {{- else if or .Values.global.storageClass .Values.arangodb.persistence.storageClass }}
  storageClassName: {{ include "capiba.storageClass" (dict "global" .Values.global "persistence" .Values.arangodb.persistence) }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.arangodb.persistence.size }}
{{- end }}
