{{- if .Values.arangodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capiba.arangodb.fullname" . }}-auth
  labels:
    {{- include "capiba.labels" . | nindent 4 }}
    {{- include "capiba.componentLabels" (dict "component" "arangodb" "context" .) | nindent 4 }}
type: Opaque
stringData:
  ARANGO_ROOT_PASSWORD: {{ .Values.arangodb.auth.rootPassword | quote }}
{{- end }}
