{{- if .Values.icebergCatalog.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capiba.icebergCatalog.fullname" . }}-secrets
  labels:
    {{- include "capiba.labels" . | nindent 4 }}
    {{- include "capiba.componentLabels" (dict "component" "iceberg-catalog" "context" .) | nindent 4 }}
type: Opaque
stringData:
  LAKEKEEPER__PG_DATABASE_URL_WRITE: {{ printf "postgres://%s:%s@%s:%v/%s" .Values.icebergCatalog.database.username .Values.icebergCatalog.database.password (include "capiba.postgresql.fullname" .) .Values.postgresql.service.port .Values.icebergCatalog.database.dbname | quote }}
  LAKEKEEPER__PG_DATABASE_URL_READ: {{ printf "postgres://%s:%s@%s:%v/%s" .Values.icebergCatalog.database.username .Values.icebergCatalog.database.password (include "capiba.postgresql.fullname" .) .Values.postgresql.service.port .Values.icebergCatalog.database.dbname | quote }}
  LAKEKEEPER__PG_ENCRYPTION_KEY: {{ .Values.icebergCatalog.pgEncryptionKey | quote }}
{{- end }}
